FROM amazonlinux:latest
ENV NODE_VERSION v7.10.0

# Install C and wget
RUN yum install gcc44 gcc-c++ libgcc44 cmake wget -y

# Install node
RUN wget http://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}.tar.gz && \
  tar -zxvf node-${NODE_VERSION}.tar.gz && \
  cd node-${NODE_VERSION} && ./configure && make && \
  make install

RUN npm install -g create-react-app
RUN mkdir /app

WORKDIR /app

