FROM ubuntu:latest

ENV ANDROID_TOOLS_VERSION 9123335
ENV ANDROID_BUILD_TOOLS_VERSION 33.0.3
ENV ANDROID_PLATFORM_VERSION 33
 
# Upgrading system
RUN apt update && apt -y install wget unzip default-jdk && apt autoclean 
 
# Download and untar Android SDK tools
RUN mkdir -p /opt/android-sdk-linux && wget https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_TOOLS_VERSION}_latest.zip -O tools.zip && \
  unzip tools.zip -d /opt/android-sdk-linux && rm tools.zip

# Set Android environment
ENV ANDROID_HOME /opt/android-sdk-linux
ENV PATH ${ANDROID_HOME}/tools:$ANDROID_HOME/platform-tools:$PATH

# Accept Android licenses
RUN yes | /opt/android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --licenses


# Update and install using sdkmanager
RUN $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" "platforms;android-${ANDROID_PLATFORM_VERSION}"
