FROM ubuntu:latest

ENV SETUP_TOOLS_VERSION="35.0.2"

# Install packages
RUN apt update && apt install -y curl python3 wget python3-dev libjpeg-dev python3-setuptools python3-venv && apt autoclean

# Install pip
#RUN cd /tmp && wget --no-check-certificate https://github.com/pypa/setuptools/archive/v${SETUP_TOOLS_VERSION}.zip
#RUN cd /tmp && unzip v${SETUP_TOOLS_VERSION}.zip
#RUN cd /tmp/setuptools-${SETUP_TOOLS_VERSION} && python35 setup.py install
RUN curl https://bootstrap.pypa.io/get-pip.py | python3 -
