FROM amazonlinux:latest

## Install packages
RUN yum -y update
RUN yum -y install python3 wget postgresql96 docker openssh-clients tar

# Install pip
RUN cd /tmp && wget --no-check-certificate https://files.pythonhosted.org/packages/67/ba/27235b9eebee2492fbf03ac1828a997d3d686031445d491f9cfa36a7085e/setuptools-66.0.0.tar.gz
RUN cd /tmp && tar -xvf setuptools-66.0.0.tar.gz
RUN cd /tmp/setuptools-66.0.0 && python3 setup.py install
RUN curl https://bootstrap.pypa.io/get-pip.py | python3 -

# Switch to python 3
RUN mv /usr/bin/python /usr/bin/python2
RUN ln -s /usr/bin/python3 /usr/bin/python

#RUN mkdir /root/.aws
RUN pip install awscli


