FROM ubuntu:latest

RUN apt update && apt install -y curl libunwind-dev libicu-dev libssl-dev && apt autoclean

ADD dotnet-install.sh /dotnet-install.sh

RUN bash /dotnet-install.sh --version latest

ENV PATH="${PATH}:/root/.dotnet"
