FROM rpheuts/env-node
ENV CHROME_BRANCH stable
ENV CHROME_VERSION 61.0.3163.100-1
ENV CHROME_PLATFORM x86_64

RUN yum install ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc -y
RUN wget http://dist.control.lth.se/public/CentOS-7/x86_64/google.x86_64/Packages/google-chrome-${CHROME_BRANCH}-${CHROME_VERSION}.${CHROME_PLATFORM}.rpm

RUN yum --nogpgcheck --skip-broken -y localinstall google-chrome-${CHROME_BRANCH}-${CHROME_VERSION}.${CHROME_PLATFORM}.rpm
RUN rpm -iph --nodeps google-chrome-${CHROME_BRANCH}-${CHROME_VERSION}.${CHROME_PLATFORM}.rpm

ADD add_missing_deps.sh /tmp/
RUN /tmp/add_missing_deps.sh /opt/google/chrome/

WORKDIR /workspace
